version: "3"

services:
  web:
    container_name: edugame_front
    image: nginx
    volumes:
      - ./Docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web-build:/app
    ports:
      - "8080:80"
